version: '2'
services:
  helloworld-mysql:
    image: mysql:5.7.20
    volumes:
      - ~/volumes/jhipster/helloworld/mysql/data/:/var/lib/mysql/
      - ~/volumes/jhipster/helloworld/mysql/init/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=testdb
    ports:
      - 3306:3306
    command: mysqld --skip-ssl --character_set_server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp --max-allowed-packet=67108864
